### ISSUE TITLE
How to provide string type for variable in Sway contract?

### ISSUE THREAD

**Issue by lzhabo** [FuelLabs/sway-libs#169]
### Motivation

Hi! I'm trying to implement the token standard and use strings from sway-libs in it, but I ran into a problem I don't understand how to pass the string from rust-sdk side. 

I have found [this code](https://github.com/boray/fuel-nomen/blob/main/utils/str-experiment/src/main.sw#L15) on your github, can you please tell me if you have code example that calls this function from rust-sdk?

I want to initial string values as variable
![Untitled](https://github.com/FuelLabs/sway-libs/assets/52199564/7e51a2be-8503-43c0-942c-30d2cbd1f6b1)

Also I tried to do it with a byte array, but I get this error:

thread 'main_test' panicked at 'called Result::unwrap() on an Err value: InvalidData("Type Struct { fields: [Bytes], generics: [] } contains nested heap types (`Vec` or `Bytes`), this is not supported.")', tests/harness.rs:20:59

**Comment by bitzoic** [comment]
This currently is not supported by the SDK. The issue can be tracked [here](https://github.com/FuelLabs/fuels-rs/issues/1011) and [here](https://github.com/FuelLabs/fuels-rs/issues/940)

**Comment by bitzoic** [comment]
Closing as this has been resolved by https://github.com/FuelLabs/fuels-rs/pull/1042
