### ISSUE TITLE
`push` symbol could not be found

### ISSUE THREAD

**Issue by iqdecay** [FuelLabs/sway-libs#172]
### Describe the bug

This piece of code cannot compile: 
```sway
contract;

use string::String;

abi MyContract {
    fn return_dynamic_string(l: u8) -> String;
}

impl MyContract for Contract {
    fn return_dynamic_string(l: u8) -> String {
        let mut string = String::new();
        let mut i = 0;
        while i < l {
            string::push(i);
            i = i+1;
        }
        string
    }
}
```

Running `forc build` yields this error: 
```bash
13 |         while i < l {
14 |             string::push(i);
   |                     ^^^^ Could not find symbol "push" in this scope.
15 |             i = i+1;
16 |         }
   |
```

I'm not sure what I'm doing wrong. 

### Steps to reproduce

1. Use `forc v0.40.1`
2. Create fresh project
3. Add
```string = { git = "https://github.com/FuelLabs/sway-libs" }``` as dependency
4. Write code above in `src/main.sw`
5. Profit?

### Minimal reproducible code example

```Rust
contract;

use string::String;

abi MyContract {
    fn return_dynamic_string(l: u8) -> String;
}

impl MyContract for Contract {
    fn return_dynamic_string(l: u8) -> String {
        let mut string = String::new();
        let mut i = 0;
        while i < l {
            string::push(i);
            i = i+1;
        }
        string
    }
}
```

### Rust Version

1.70.0

### Forc Version

0.40.1

### Expected behavior

I expect the `push` symbol can be found without adding other imports.

**Comment by bitzoic** [comment]
This will work:

contract;

use string::String;

abi MyContract {
    fn return_dynamic_string(l: u8) -> String;
}

```
impl MyContract for Contract {
    fn return_dynamic_string(l: u8) -> String {
        let mut string = String::new();
        let mut i = 0;
        while i < l {
            string.push(i);
            i = i+1;
        }
        string
    }
}
```

**Comment by bitzoic** [comment]
`push()` is an implementation on self while `new()` returns Self.

**Comment by bitzoic** [comment]
Please note that the `String` type in Sway-Libs will be removed in favor of https://github.com/FuelLabs/sway/pull/4716 in the std-lib

**Comment by iqdecay** [comment]
Whoopsie haha, sorry  I got confused reading the readme, closing the issue.
