### ISSUE TITLE
Specification missing function parameters

### ISSUE THREAD

**Issue by calldelegation** [FuelLabs/sway-libs#177]
### Motivation

In all of the libraries i.e. [NFT](https://github.com/FuelLabs/sway-libs/blob/master/libs/nft/SPECIFICATION.md) are missing function parameters that tell the user how to use the specific function. 

It has been brought up in the forum [here](https://forum.fuel.network/t/sway-libs-nft-library/2893/5)

**Comment by postmeback** [comment]
Can you explain a bit more ?

**Comment by bitzoic** [comment]
Closing as this library no longer exists
