### ISSUE TITLE
fixed_point: Variable declaration's type annotation does not match up with the assigned expression's type

### ISSUE THREAD

**Issue by PaulRBerg** [FuelLabs/sway-libs#188]
I tried using the `fixed_point` library in a forc v0.44.1 project, but I couldn't compile it. Here's a link with all the errors I got:

https://app.warp.dev/block/WG1ilo8DJAiptYGBrC7j3K

**Comment by bitzoic** [comment]
An update to bump the repository to force v0.44.1 was merged and released this morning. https://github.com/FuelLabs/sway-libs/pull/185

Please ensure your project is using the `v0.13.0` release
