### ISSUE TITLE
Latest commit to sway-libs broke floats library

### ISSUE THREAD

**Issue by johnquid** [FuelLabs/sway-libs#203]
error just happens from importing the library (even after all usage of the underlying components has been commented out)

<img width="1440" alt="Screenshot 2023-11-14 at 21 38 25" src="https://github.com/FuelLabs/sway-libs/assets/78568736/3114d55e-5d98-4712-8768-ec94569e8b60">
<img width="1440" alt="Screenshot 2023-11-14 at 21 38 15" src="https://github.com/FuelLabs/sway-libs/assets/78568736/18613241-d9e0-43ac-bb6c-15743fcc5b30">
<img width="1440" alt="Screenshot 2023-11-14 at 21 38 07" src="https://github.com/FuelLabs/sway-libs/assets/78568736/5591f9af-1aa7-4e33-95c8-b3a7c4dc546e">
<img width="1440" alt="Screenshot 2023-11-14 at 21 37 55" src="https://github.com/FuelLabs/sway-libs/assets/78568736/959fef04-65ca-4a12-8f00-0c861116b12a">
sway-lib-std

**Comment by bitzoic** [comment]
This is a mismatch of forc versions. 
- The v0.15.0 release of sway-libs is using forc v0.46.1
- The v0.16.0 release of sway-libs is using forc v0.47.0
These are not interchangeable
