### ISSUE TITLE
Problems with signed integers 

### ISSUE THREAD

**Issue by Vid201** [FuelLabs/sway-libs#267]
### Describe the bug

There seems to be a problem with signed integer implementations. I noticed two issues:
- this test is failing for me (https://github.com/FuelLabs/sway-libs/blob/master/tests/src/signed_integers/signed_i128/src/main.sw)
- I think there is a problem with subtraction implementation. For example, I128(0) - I128(-50) results in I128(-50), but should be I128(50)

### Steps to reproduce

1. Run tests for signed integers

### Minimal reproducible code example

```Rust
let u128_5 = U128::from((0, 5));
let i128_neg5 = I128::neg_from(u128_5);
assert((I128::zero() - i128_neg5) == I128::from(u128_5)); // bug, this should pass
```

### Rust Version

rustc 1.79.0 (129f3b996 2024-06-10)

### Forc Version

forc 0.62.0

### Expected behavior

Subtraction should return correct result.
All tests in the repo for signed integers should pass.

**Comment by bitzoic** [comment]
Resolved by https://github.com/FuelLabs/sway-libs/pull/268
