### ISSUE TITLE
CI runner for scripts

### ISSUE THREAD

**Issue by rostyslavtyshko** [FuelLabs/sway-libs#44]
We need to add a job to run CI scripts as in the main `sway` repository

**Comment by simonr0204** [comment]
This seems like a high priority. Is anybody working on this?

**Comment by bitzoic** [comment]
Closing this issue as this doesn't seem relevant anymore. Workspaces are now used with https://github.com/FuelLabs/sway-libs/issues/72 which builds and runs all scripts.
