### ISSUE TITLE
pseudo-random library

### ISSUE THREAD

**Issue by GearedPaladin** [FuelLabs/sway-libs#48]
### Description
A pseudo-random library that allows easy creation of random values. Not suitable for applications such as gambling as the result will be pre-calculable

### Features
I have already implemented the following features
- Random b256
- Random B512
- Random bool
- Random u64
- Random U128
- Random U256
- A Vec populated of random u64s of any given length
- Random u64 in a given range
- A Vec populated of random u64s of any given length in any given range
- A random item from a Vec
- Shuffling of a Vec

Once F64, F128 are completed I will feature them aswell

### Suggestions
Please write additional features that you would like to see in this library

**Comment by adlerjohn** [comment]
What are the applications for this feature?

**Comment by GearedPaladin** [comment]
> What are the applications for this feature?

As long as Fuel is PoA it can be used for lotteries as a much cheaper alternative to oracles knowing that miner manipulation wont occur.
Other than that this is mostly useful for web3 games where the potential gain from trying to manipulate the block is much lower than the cost of doing so, think XP gained from killing a monster (usually a random amount in a range). You could use an oracle for tasks like this but the cost would be too high (for reference its about $0.004 per 500 random numbers on Polygon, not to mention you would need to hold LINK tokens to be able to do this)

**Comment by SwayStar123** [comment]
Hey what is the status on this?

**Comment by bitzoic** [comment]
Closing as not planned
