### ISSUE TITLE
Make NFTCore `approve` function public

### ISSUE THREAD

**Issue by supiket** [FuelLabs/sway-libs#52]
### Motivation

While updating the `sway_libs` version to the latest one (0.4.0) in the dependencies of a contract in the Sway Applications repo, I am getting the following error using `forc 0.31.1` to build:

```   |
33 |
34 |     require(nft.is_some(), InputError::TokenDoesNotExist);
35 |     nft.unwrap().approve(approved);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Calling private library method approve is not allowed.
36 | }
   |
____
```

I suggest making the [`approve` function ](https://github.com/FuelLabs/sway-libs/blob/master/sway_libs/src/nft/nft_core.sw#L31)public if there is nothing preventing it.

**Comment by bitzoic** [comment]
Thanks for catching this, never even noticed!
