### ISSUE TITLE
Contract Owner Library

### ISSUE THREAD

**Issue by bitzoic** [FuelLabs/sway-libs#53]
#### Description

In Solidity, a common library that is used is the `ownerOf` modifier. This allows for developers to ensure a function cannot be called unless a specific user is the caller.

Sway should have a similar feature that easily allows for developers to setup an owner of a contract.

#### Motivation

Contracts often require owner privileges.

**Comment by djma** [comment]
Just making sure, you're referring to `onlyOwner`, as implemented [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable.sol) right?

I could take a stab at it.
