### ISSUE TITLE
Replace "signed" with "unsigned" in fixed-point libs. 

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/sway-libs#98]
### Describe the bug

There are instances in the docs and code where "signed is used, but it should be "unsigned", i.e:
- https://github.com/FuelLabs/sway-libs/tree/master/libs/fixed_point#basic-functionality
- https://github.com/FuelLabs/sway-libs/blob/55a1a3d5d0fcce55997dc31ce18369154088fa23/libs/fixed_point/src/ufp64.sw#L2

### Steps to reproduce

Read the code.

### Minimal reproducible code example

```Rust
Master branch of sway-libs/fixed-point.
```

### Rust Version

1.67

### Forc Version

latest

### Expected behavior

Replace the word "signed" with "unsigned"

**Comment by bitzoic** [comment]
cc @rostyslavtyshko @tyshkor
